
datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/dts
  username: root
  password: 123456
  maxActive: 15
  minIdle: 5


app:
  name: server
  group: Default
  port: 9876
  zkAddress: localhost:2181